In [2]:
using LinearAlgebra, Plots, Random, Distributions, NLsolve

First, let us create a NamedTuple with our parameters.

In [1]:
params = (; β = 0.72, # bargaining_power
            r = 0.012, # discount rate
            λ = 4, # arrival rate
            z = 0.4, # value of leisure
            p_star = 1., # productivity
            s_star = 0.1, # separation rate
            c = 0.213, # cost of vacancy
            σ = 0.0165, # standard deviation 
            γ = 0.004, # autoregressive coefficient
            n = 2001, # gridpoints
            lb = -1., # bounds for grid
            ub = 1., # bounds for grid
            mc = 1.355, # constant term in matching function
            me = -0.72, # exponent in matching function
            max_iter  = 1000, # maximum number of iterations
            agents = 10000, # number of agents
            periods = 1212, # number of periods
            seed1 = 10, # seed1 for random number generator
            seed2 = 4, # seed2 for random number generator
            seed3 = 11 ) # seed3 for random number generator 

(β = 0.72, r = 0.012, λ = 4, z = 0.4, p_star = 1.0, s_star = 0.1, c = 0.213, σ = 0.0165, γ = 0.004, n = 2001, lb = -1.0, ub = 1.0, mc = 1.355, me = -0.72, max_iter = 1000, agents = 10000, periods = 1212, seed1 = 10, seed2 = 4, seed3 = 11)

In [3]:
function matching_function(grid, params)
    (; mc, me) = params
    return mc .* (grid .^ me)
end

matching_function (generic function with 1 method)

In [4]:
function generate_income_process(params)
    (; n, lb, ub) = params
    Δ = ub / n
    grid = LinRange(lb, ub, n)
    exp_grid = exp.(grid)
    transition_matrix = zeros(n, n)
    for i in 1:n
        if i == 1
            transition_matrix[i, i] = ( 1/2 ) * (1 .+ (grid[i] / (n*Δ)))
            transition_matrix[i, i+1] = ( 1/2 ) * (1 .- (grid[i] / (n*Δ)))
        elseif i == n
            transition_matrix[i, i-1] = ( 1/2 ) * (1 .+ (grid[i] / (n*Δ)))
            transition_matrix[i, i] = ( 1/2 ) * (1 .- (grid[i] / (n*Δ)))
        else
            transition_matrix[i, i-1] = ( 1/2 ) * (1 .+ (grid[i] / (n*Δ)))
            transition_matrix[i, i+1] = ( 1/2 ) * (1 .- (grid[i] / (n*Δ)))
        end
    end
    return exp_grid, transition_matrix
end

income_process, transition_matrix = generate_income_process(params)

([0.36787944117144233, 0.3682475046136629, 0.3686159363034188, 0.3689847366091417, 0.369353905899632, 0.3697234445440589, 0.3700933529119613, 0.37046363137324734, 0.37083428029819565, 0.37120530005745517  …  2.6939270528874992, 2.696622327353013, 2.6993202984410796, 2.7020209688496686, 2.7047243412794524, 2.7074304184338023, 2.7101392030187967, 2.7128506977432196, 2.715564905318567, 2.718281828459045], [0.0 1.0 … 0.0 0.0; 0.0004999999999999449 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0004999999999999449; 0.0 0.0 … 1.0 0.0])

In [5]:
function productivity_grid(params)
    (; z, p_star) = params
    grid = generate_income_process(params)
    p_grid = z .+ (grid[1] .* (p_star - z))
    return p_grid
end

function separation_grid(params)
    (; n, s_star) = params
    grid = generate_income_process(params)
    s_grid = grid[1] .* s_star
    return s_grid
end

function theta_grid(params)
    (; n) = params
    grid = generate_income_process(params)
    θ_grid = LinRange(0.1,3,n)
    return θ_grid
end

theta_grid (generic function with 1 method)

In [6]:
function iterate_prod(grid, params)
    (; β, r, λ, z, p_star, s_star, c, σ, γ, n, lb, ub, mc, me, max_iter) = params
    Δ = ub / n
    exp_grid, transition_matrix = generate_income_process(params)
    prod_grid = productivity_grid(params)
    iter = 0
    error = Inf
    new_grid = zeros(n)
    while iter < max_iter && error > 0.001
        iter += 1
        match_grid = matching_function(grid, params)
        for i in 1:n
            if i == 1
                result = nlsolve(theta -> - ((r+s_star+λ) / match_grid[i]) + (((1-β)*(prod_grid[i]-z)) / c ) - β*theta[1] + λ*((transition_matrix[i, i+1] / match_grid[i+1])), [grid[i]])
                new_grid[i] = result.zero[1]
            elseif i == n
                result = nlsolve(theta -> - ((r+s_star+λ) / match_grid[i]) + (((1-β)*(prod_grid[i]-z)) / c ) - β*theta[1] + λ*((transition_matrix[i, i-1] / match_grid[i-1])), [grid[i]])
                new_grid[i] = result.zero[1]
            else
                result = nlsolve(theta -> - ((r+s_star+λ) / match_grid[i]) + (((1-β)*(prod_grid[i]-z)) / c ) - β*theta[1] + λ*((transition_matrix[i, i-1] / match_grid[i-1]) + (transition_matrix[i, i+1] / match_grid[i+1])), [grid[i]])
                new_grid[i] = result.zero[1]
            end
        end
        error = norm(new_grid - grid)
        grid = copy(new_grid)
        if iter % 1 == 0
            println("Iteration: $iter, Error: $error")
        end
    end
    return grid
end

θ_grid = theta_grid(params)
thetas = iterate_prod(θ_grid, params)

Iteration: 1, Error: 22.24042821451652
Iteration: 2, Error: 1.645337822710512
Iteration: 3, Error: 0.13490677881814264
Iteration: 4, Error: 0.012028792790704025
Iteration: 5, Error: 0.0012228452433972544
Iteration: 6, Error: 0.00014429373642639175


2001-element Vector{Float64}:
 0.3504679344054823
 0.3508306262460641
 0.3511936493759864
 0.3515570985052328
 0.351920871184671
 0.3522850393677497
 0.35264958272735075
 0.3530144697176859
 0.3533797712593901
 0.35374541566147344
 ⋮
 2.7124282294989412
 2.7151998609556762
 2.717974312261973
 2.7207515685657864
 2.723531674825363
 2.726314585161308
 2.7291003336030744
 2.7318889231898624
 2.734680325969482

In [7]:
function iterate_sep(grid, params)
    (; β, r, λ, z, p_star, s_star, c, σ, γ, n, lb, ub, mc, me, max_iter) = params
    Δ = ub / n
    exp_grid, transition_matrix = generate_income_process(params)
    sep_grid = separation_grid(params)
    iter = 0
    error = Inf
    new_grid = zeros(n)
    while iter < max_iter && error > 0.001
        iter += 1
        match_grid = matching_function(grid, params)
        for i in 1:n
            if i == 1
                result = nlsolve(theta -> - ((r+sep_grid[i]+λ) / match_grid[i]) + (((1-β)*(p_star-z)) / c ) - β*theta[1] + λ*((transition_matrix[i, i+1] / match_grid[i+1])), [grid[i]])
                new_grid[i] = result.zero[1]
            elseif i == n
                result = nlsolve(theta -> - ((r+sep_grid[i]+λ) / match_grid[i]) + (((1-β)*(p_star-z)) / c ) - β*theta[1] + λ*((transition_matrix[i, i-1] / match_grid[i-1])), [grid[i]])
                new_grid[i] = result.zero[1]
            else
                result = nlsolve(theta -> - ((r+sep_grid[i]+λ) / match_grid[i]) + (((1-β)*(p_star-z)) / c ) - β*theta[1] + λ*((transition_matrix[i, i-1] / match_grid[i-1]) + (transition_matrix[i, i+1] / match_grid[i+1])), [grid[i]])
                new_grid[i] = result.zero[1]
            end
        end
        error = norm(new_grid - grid)
        grid = copy(new_grid)
        if iter % 1 == 0
            println("Iteration: $iter, Error: $error")
        end
    end
    return grid
end

θ_grid = theta_grid(params)
sep_thetas = iterate_sep(θ_grid, params)
    

Iteration: 1, Error: 54.000472622261384
Iteration: 2, Error: 7.700569011569239
Iteration: 3, Error: 1.4943263408370036
Iteration: 4, Error: 0.29482678774158727
Iteration: 5, Error: 0.0614452372134459
Iteration: 6, Error: 0.013214677460164956
Iteration: 7, Error: 0.002923860883392916
Iteration: 8, Error: 0.000711446442226081


2001-element Vector{Float64}:
 1.0437770409880436
 1.0437396761402775
 1.0437019834920682
 1.043664469796426
 1.0436265391864397
 1.0435891756585358
 1.0435511573978233
 1.0435135185145556
 1.043475639612994
 1.0434378362402184
 ⋮
 0.8411663056806334
 0.8410053785000571
 0.8407777146815644
 0.8405965475521828
 0.8403823477397983
 0.8401908473220112
 0.8399995931775783
 0.8397657141037753
 0.8396222563331162

In [8]:
function bargaining_grid(params)
    (; n) = params
    lower_bound = 0.64
    upper_bound = 0.80
    grid = LinRange(lower_bound, upper_bound, n)    
    return reverse(grid)
end

barg_grid = bargaining_grid(params)

2001-element LinRange{Float64, Int64}:
 0.8, 0.79992, 0.79984, 0.79976, 0.79968, …, 0.64024, 0.64016, 0.64008, 0.64

In [9]:
function iterate_prod_barg(grid, params)
    (; r, λ, z, p_star, s_star, c, σ, γ, n, lb, ub, mc, me, max_iter) = params
    Δ = ub / n
    exp_grid, transition_matrix = generate_income_process(params)
    prod_grid = productivity_grid(params)
    β = bargaining_grid(params)
    iter = 0
    error = Inf
    new_grid = zeros(n)
    while iter < max_iter && error > 0.001
        iter += 1
        match_grid = matching_function(grid, params)
        for i in 1:n
            if i == 1
                result = nlsolve(theta -> - ((r+s_star+λ) / match_grid[i]) + (((1-β[i])*(prod_grid[i]-z)) / c ) - β[i]*theta[1] + λ*((transition_matrix[i, i+1] / match_grid[i+1])), [grid[i]])
                new_grid[i] = result.zero[1]
            elseif i == n
                result = nlsolve(theta -> - ((r+s_star+λ) / match_grid[i]) + (((1-β[i])*(prod_grid[i]-z)) / c ) - β[i]*theta[1] + λ*((transition_matrix[i, i-1] / match_grid[i-1])), [grid[i]])
                new_grid[i] = result.zero[1]
            else
                result = nlsolve(theta -> - ((r+s_star+λ) / match_grid[i]) + (((1-β[i])*(prod_grid[i]-z)) / c ) - β[i]*theta[1] + λ*((transition_matrix[i, i-1] / match_grid[i-1]) + (transition_matrix[i, i+1] / match_grid[i+1])), [grid[i]])
                new_grid[i] = result.zero[1]
            end
        end
        error = norm(new_grid - grid)
        grid = copy(new_grid)
        if iter % 1 == 0
            println("Iteration: $iter, Error: $error")
        end
    end
    return grid
end

θ_grid = theta_grid(params)
thetas_barg = iterate_prod_barg(θ_grid, params)

Iteration: 1, Error: 20.095365965672737
Iteration: 2, Error: 1.5756105466694514
Iteration: 3, Error: 0.13157801754922868
Iteration: 4, Error: 0.01142946280340591
Iteration: 5, Error: 0.0010867025345807162
Iteration: 6, Error: 0.00012097652090862869


2001-element Vector{Float64}:
 0.22514867331977384
 0.22549511191916263
 0.22584201765365652
 0.2261894348516834
 0.2265373416182277
 0.22688574386916102
 0.2272346394659428
 0.2275840402300056
 0.22793393091317585
 0.22828432428018341
 ⋮
 3.904921692787293
 3.9102604083157284
 3.9156063117875815
 3.920959357162226
 3.9263195420176134
 3.9316869376197885
 3.937061459077796
 3.942443251550919
 3.9478321392164313

In [10]:
function iterate_sep_barg(grid, params)
    (; r, λ, z, p_star, s_star, c, σ, γ, n, lb, ub, mc, me, max_iter) = params
    Δ = ub / n
    exp_grid, transition_matrix = generate_income_process(params)
    sep_grid = separation_grid(params)
    β = bargaining_grid(params)
    iter = 0
    error = Inf
    new_grid = zeros(n)
    while iter < max_iter && error > 0.001
        iter += 1
        match_grid = matching_function(grid, params)
        for i in 1:n
            if i == 1
                result = nlsolve(theta -> - ((r+sep_grid[i]+λ) / match_grid[i]) + (((1-β[i])*(p_star-z)) / c ) - β[i]*theta[1] + λ*((transition_matrix[i, i+1] / match_grid[i+1])), [grid[i]])
                new_grid[i] = result.zero[1]
            elseif i == n
                result = nlsolve(theta -> - ((r+sep_grid[i]+λ) / match_grid[i]) + (((1-β[i])*(p_star-z)) / c ) - β[i]*theta[1] + λ*((transition_matrix[i, i-1] / match_grid[i-1])), [grid[i]])
                new_grid[i] = result.zero[1]
            else
                result = nlsolve(theta -> - ((r+sep_grid[i]+λ) / match_grid[i]) + (((1-β[i])*(p_star-z)) / c ) - β[i]*theta[1] + λ*((transition_matrix[i, i-1] / match_grid[i-1]) + (transition_matrix[i, i+1] / match_grid[i+1])), [grid[i]])
                new_grid[i] = result.zero[1]
            end
        end
        error = norm(new_grid - grid)
        grid = copy(new_grid)
        if iter % 1 == 0
            println("Iteration: $iter, Error: $error")
        end
    end
    return grid
end

θ_grid = theta_grid(params)
sep_thetas = iterate_sep_barg(θ_grid, params)

Iteration: 1, Error: 45.474316076776056
Iteration: 2, Error: 6.846475992927783
Iteration: 3, Error: 1.3201216451684383
Iteration: 4, Error: 0.26430013613346603
Iteration: 5, Error: 0.055789793551270284
Iteration: 6, Error: 0.012175779014866875
Iteration: 7, Error: 0.0027348862772769906
Iteration: 8, Error: 0.0006594973776237966


2001-element Vector{Float64}:
 0.6713666915893561
 0.6716778304360874
 0.6719889380856261
 0.6723001499223206
 0.672611201407783
 0.6729225294044114
 0.6732336434657564
 0.6735449124293169
 0.6738562003486475
 0.6741673679889543
 ⋮
 1.2079839606664111
 1.2081191258054373
 1.2082316062953533
 1.2083532277483562
 1.208469303179048
 1.208599629669544
 1.2087045705270776
 1.20883275541049
 1.2089486087360286

In [11]:
function generate_poisson_matrix(params)
    (;agents, periods, λ) = params
    dist = Poisson(λ)
    matrix = rand(dist, agents, periods)
    matrix[matrix .!= λ] .= 0.0
    matrix[matrix .!= 0.0] .= 1.0
    return matrix
end

arrival_matrix = generate_poisson_matrix(params)

10000×1212 Matrix{Int64}:
 0  0  0  1  0  0  0  0  0  0  0  0  0  …  1  0  0  0  1  0  0  1  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  1     0  1  0  0  0  0  0  0  0  0  1  0
 1  0  1  0  0  0  1  0  0  0  0  0  0     0  0  0  0  1  0  0  1  1  0  0  0
 0  0  0  0  1  0  0  0  0  0  0  0  0     1  0  0  1  0  0  0  1  0  1  0  1
 0  0  0  0  0  1  0  1  0  0  0  0  0     0  0  1  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  1  0  0  0  …  0  0  0  1  0  0  0  1  1  0  0  0
 1  0  0  1  1  0  0  1  0  0  0  1  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  1  0  0  0     0  1  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  1  0  0  0  0  1  0  0  0     0  0  0  0  1  0  0  0  0  0  0  0
 0  0  1  0  1  1  0  0  0  0  0  0  0     0  0  0  0  0  1  0  1  0  0  0  0
 ⋮              ⋮              ⋮        ⋱  ⋮              ⋮              ⋮  
 0  1  0  1  1  1  0  0  0  1  1  0  0     1  0  0  0  0  0  1  0  0  0  0  1
 0  0  0  0  0  0  0  0  0  0  0  1  1 

In [12]:
function generate_sep_matrix(params)
    (;agents, periods, seed1) = params
    Random.seed!(seed1)
    dist = Uniform(0., 1.)
    matrix = rand(dist, agents, periods)
    matrix[matrix .> 0.1] .= 0.0
    matrix[matrix .!= 0.0] .= 1.0
    return matrix
end

sep_matrix = generate_sep_matrix(params)

10000×1212 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  …  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     1.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  1.0  0.0  1.0  0.0  0.0  0.0
 ⋮                        ⋮              ⋱  ⋮                        ⋮    
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [13]:
function generate_matching_matrix(params)
    (;agents, periods, seed2) = params
    Random.seed!(seed2)
    dist = Uniform(0., 1.)
    matrix = rand(dist, agents, periods)
    matrix[matrix .> 0.1] .= 0
    matrix[matrix .!= 0] .= 1
    return matrix
end

match_matrix = generate_matching_matrix(params)

10000×1212 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  …  0.0  0.0  1.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  1.0  0.0  0.0
 ⋮                        ⋮              ⋱  ⋮                        ⋮    
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0

In [14]:
function generate_prod_transition(params)
    (;agents, periods, seed3) = params
    Random.seed!(seed3)
    dist = Uniform(0., 1.)
    matrix = rand(dist, agents, periods)
    return matrix
end

prod_matrix = generate_prod_transition(params)

10000×1212 Matrix{Float64}:
 0.498434   0.585734   0.985208  0.999441   …  0.342879  0.078236   0.504942
 0.389721   0.026066   0.247143  0.247694      0.239191  0.641298   0.727137
 0.26454    0.34855    0.378233  0.972243      0.785603  0.896256   0.554438
 0.719424   0.154686   0.200103  0.388903      0.823439  0.598008   0.481704
 0.676602   0.407505   0.172377  0.813863      0.190301  0.696302   0.548427
 0.184079   0.420168   0.60244   0.0814761  …  0.963862  0.801936   0.772113
 0.46979    0.0874775  0.186148  0.462649      0.687425  0.614549   0.162676
 0.568002   0.291676   0.656595  0.234738      0.73693   0.352198   0.247666
 0.51084    0.595823   0.879028  0.0144836     0.693407  0.808572   0.578294
 0.350315   0.954622   0.858298  0.800742      0.313513  0.14208    0.362558
 ⋮                                          ⋱            ⋮          
 0.521484   0.222765   0.345987  0.990903      0.354768  0.917699   0.447622
 0.0393032  0.453307   0.477486  0.232969      0.652574 